### ISSUE TITLE
FillRand improving

### ISSUE THREAD

**Issue by okovtun** [remiz71/Functions#3]
I think we can go farther to improve our skills with new tasks, if you have time and desire.
The next task is:
Try to modify FillRand() function to generate random numbers in defined range of values, from some min to some max. Some extra parameters are necessary for this task (minRand, maxRand). You may also use default values in parameters for this.
All about default parameters you can find here: http://cplusplus.com/doc/tutorial/functions/
Try to solve this using branching and PullRequest.
If you have any questions fill free to communicate over WhatsApp.
Have a nice day :-)

**Comment by remiz71** [comment]
_Ok, I will try improve these function ASAP ;)_

**Comment by remiz71** [comment]
@okovtun MinRand and MaxRand we input from keyboard?
 
UPD: Sorry, I read twice and understood, that we can use default values🤓
